FROM node:18.15.0-alpine as builder	


RUN mkdir /app
WORKDIR /app	
ENV PATH /app/node_modules/.bin:$PATH	
COPY package.json /app/package.json

RUN npm install

COPY . /app
CMD ["npm", "run", "server"]

